services:
  kursi-roda-fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kursi-roda-fastapi
    volumes:
      - .:/app
    depends_on:
      - db_fastapi
    environment:
      - DATABASE_URL=postgresql://ilham:Rahasia123@db_fastapi/db_fastapi

  kursi-roda-postgres:
    image: postgres:13-alpine
    container_name: kursi-roda-postgres
    environment:
      POSTGRES_USER: ilham
      POSTGRES_PASSWORD: Rahasia123
      POSTGRES_DB: db_fastapi
    volumes:
      - db_fastapi_data:/var/lib/postgresql/data
      

volumes:
  db_fastapi_data:

