name: Deploy FastAPI app to VPS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          
      - name: Sync dependencies and code to VPS
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.USER }}/gii/kursi-roda/kursi-roda-fastapi/app/
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" venv/ ${{ secrets.USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.USER }}/gii/kursi-roda/kursi-roda-fastapi/venv/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}


