name: Deploy FastAPI to VPS

on:
    push:
        branches: [main]

jobs:
    build-dependencies:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.13"

            - name: Create Virtual Environment
              run: |
                  python -m venv venv
                  source venv/bin/activate
                  pip install -r requirements.txt

            - name: Package Dependencies
              run: |
                  tar -czvf dependencies.tar.gz -C venv/lib/python3.13/site-packages .

            - name: Transfer Dependencies to VPS
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  port: ${{ secrets.VPS_PORT }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  source: "dependencies.tar.gz"
                  target: "/home/dean-cloud/gii/kursi-roda/kursi-roda-fastapi/"

    deploy:
        runs-on: ubuntu-latest
        needs: build-dependencies

        steps:
            - name: Deploy via SSH
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  port: ${{ secrets.VPS_PORT }}
                  key: ${{ secrets.VPS_SSH_KEY }}
                  script: |
                      cd /home/dean-cloud/gii/kursi-roda/kursi-roda-fastapi
                      git pull origin main
                      tar -xzvf dependencies.tar.gz -C venv/lib/python3.13/site-packages
