name: Deploy FastAPI app to VPS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 139.59.224.190 >> ~/.ssh/known_hosts

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m venv venv
          venv/bin/pip install -r requirements.txt

      - name: Sync dependencies and code to VPS
        run: |
          rsync -avz ./ dean-cloud@139.59.224.190:/home/dean-cloud/gii/kursi-roda/kursi-roda-fastapi/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
