name: Deploy FastAPI app to VPS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          
      - name: Add SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          chmod 644 ~/.ssh/known_hosts

      - name: Sync code and dependencies to VPS
        run: |
          rsync -avz --delete ./ dean-cloud@${{ secrets.VPS_HOST }}:/home/dean-cloud/gii/kursi-roda/kursi-roda-fastapi/
          rsync -avz --delete venv/ dean-cloud@${{ secrets.VPS_HOST }}:/home/dean-cloud/gii/kursi-roda/venv/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}


